version = 1

[[annotations]]
path = [
    ".flake8",
    ".github/**",
    ".gitignore",
    ".pre-commit-config.yaml",
    "FAQs.md",
    "benchmarks/**",
    "evals/**",
    "examples/**",
    "fla/**",
    "legacy/**",
    "scripts/**",
    "setup.py",
    "tests/**",
    "utils/**"
]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright © 2023-2025, Songlin Yang, Yu Zhang"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "pyproject.toml",
    "fla/layers/attn.py",
    "fla/layers/gated_deltanet.py",
    "fla/layers/lte.py",
    "fla/layers/nsa.py",
    "fla/layers/utils.py ",
    "fla/models/__init__.py",
    "fla/models/hybrid_gated_deltanet/**",
    "fla/modules/rotary.py",
    "fla/ops/lte/parallel.py ",
    "fla/ops/nsa/compression.py",
    "fla/ops/nsa/naive.py",
    "fla/ops/nsa/parallel.py",
    "train.sh",
    "README.md",
    "configs/*"
]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright © 2023-2025, Songlin Yang, Yu Zhang", "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"]
SPDX-FileContributor = "Mutian He <mutian.he@idiap.ch>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "assets/*.png",
    "fla/ops/lte/__init__.py",
    "fla/ops/lte/cache.py",
    "fla/ops/lte/cache_fast.py ",
    "fla/ops/lte/utils.py",
    "lte_utils.py",
    "requirements.txt",
    "tests/ops/test_nsa.py",
]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"
SPDX-FileContributor = "Mutian He <mutian.he@idiap.ch>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "train.py"
    ]
precedence = "closest"
SPDX-FileCopyrightText= [
    "Copyright © Meta Platforms, Inc. and affiliates.",
    "Copyright © 2025, Yu Zhang, Songlin Yang",
    "Copyright © 2025 Idiap Research Institute <contact@idiap.ch>"
]
SPDX-FileContributor = "Mutian He <mutian.he@idiap.ch>"
SPDX-License-Identifier = "MIT"
